USE [Quiz]
GO

INSERT INTO [dbo].[Question]
           ([QuestionText]
           ,[CategoryFK])
     VALUES
('Melyik magyar festőművész alkotása a Golgota?','1'),
('Kinek az alkotása a Magányos cédrus?','1'),
('Hol tekinthető meg a Feszty-körkép?','1'),
('Melyik festő volt kedvenc témája a napraforgók?','1'),
('Kinek a műve a Mona Lisa?','1'),
('Hol van kiállítva a Mona Lisa?','1'),
('Milyen nemzetiségű volt Pablo Picasso?','1'),
('Kinek a műve a Don Quijote szobra Spanyolországban?','1'),
('Mi található a párizsi Louvre udvarán?','1'),
('Hány üveglapból áll ez az üvegpiramis?','1'),
('Mikor alapították a firenzei Uffizi Képtárat?','1'),
('Mi volt Victor Vasarely születési neve?','1'),
('Melyik festő alkotásai a Majális és a Lilaruhás nő?','1'),
('Hol született Munkácsy Mihály?','1'),
('Melyik festő alkotása a Honfoglalás?','1'),
('Mi Amerigo Tot szobrászművész eredeti neve?','1'),
('Melyik testrészét vágta le Vincent van Gogh?','1'),
('Melyik festő műve a Karácsonyi éj?','1'),
('Miből készült a "Boci" szobor Budapesten?','1'),
('Kinek a festménye a Vénusz születése?','1'),
('Hol született Victor Vasarely festő?','1'),
('Melyik festő műve a Krisztus trilógia?','1'),
('Hány festményt loptak el 1983-ban a Szépművészeti Múzeumból?','1'),
('Melyik szobrász alkotása a Diszkoszvető?','1'),
('Kinek a festménye az Éjjeli őrjárat?','1'),
('Melyik magyar festő alkotása a Majális?','1'),
('Kinek az alkotása a Magányos cédrus?','1'),
('Kinek a festménye a Mona Lisa?','1'),
('Mit csinál az inas Munkácsi Mihály festményén?','1'),
('Ki volt Szinyei Merse Pál?','1'),
('Ki volt Rippl-Rónai József?','1'),
('Hol látható Munkácsy Mihály: Honfoglalás c. festménye?','1'),
('Melyik költő verse a Héja-nász az avaron?','2'),
('Hány kötetből áll a Harry Potter?','2'),
('Hol született Petőfi Sándor?','2'),
('2002-ben ki kapott irodalmi Nobel-díjat?','2'),
('Mi volt a Harry Potter első kötetének a címe?','2'),
('Ki írta a Holt Vidék c. verset?','2'),
('Ki volt Gandalf a Gyűrűk Ura trilógiában?','2'),
('Hány köteltből áll a Twilight (Alkonyat) c. fantasyregény?','2'),
('Ki a főszereplője a Remény rabjai c. filmnek?','2'),
('Ki írta a A walesi bárdok c. verset?','2'),
('Ki volt a nagy mesemondó?','2'),
('Ki írta Az aranyember c. regényt?','2'),
('Hogy hívták János Vitézt a mű elején?','2'),
('Ki írta a Vanitatum Vanitas c. verset?','2'),
('Hogy hívták Don Quijote lovát?','2'),
('Ki Harry Potter?','2'),
('Kinek a regénye az Isten rabjai?','2'),
('Ki volt Esterházy Péter az író  édesapja?','2'),
('Kinek a műve a Háry János?','2'),
('Milyen fajtájú kutya volt Niki Déry Tibor kisregényében?','2'),
('Ki írta az Énekek éneke c. verset?','2'),
('Kinek a műveiben szerepel Fülig Jimmy?','2'),
('Ki volt Ady Endre házastársa?','2'),
('Kinek a regénye Az öreg halász és a tenger?','2'),
('Melyik nem a három nővér egyike Csehov drámájában?','2'),
('Mi a műfaja Szophoklész művének az Antigonénak?','2'),
('Melyk író álneve volt a P.Howard?','2'),
('Milyen jelzővel illették Romhányi József írót?','2'),
('Melyik olasz városba játszódik a Rómeó és Júlia?','2'),
('Melyik stílus legnagyobb alakja volt Vörösmarty Mihály?','2'),
('Ki írta a Tartozkodó kérelem c. verset?','2'),
('Milyen nemzetiségű regény A kis herceg?','2'),
('Kinek a műve a Liliomfi?','2'),
('Kinek a regénye A gólyakalifa?','2'),
('Hányszoros Kossuth-díjas Illyés Gyula?','2'),
('Hol született Jókai Mór?','2'),
('Melyik költőnk volt szegedi?','2'),
('Kinek a regénye A Da Vinci-kód?','2'),
('Melyik írónk volt bridzsversenyző?','2'),
('Melyik nem William Shakespeare műve?','2'),
('Ki Hamlet Shakespeare tragédiájában?','2'),
('Ki írta a Toldit?','2'),
('Kinek a műve A kaukázusi krétakör?','2'),
('Melyik nem Gorkij drámája?','2'),
('Milyen nemzetiségű volt George Bernard Shaw?','2'),
('Milyen állat Vuk Fekete István regényében?','2'),
('Kinek a műve a Nemo kapitány?','2'),
('Ki írta A kőszívű ember fiai c. regényt?','2'),
('Ki írta a Himnuszt?','2'),
('Ki zenésítette meg a Szózatot?','2'),
('Milyen sportot űzött Erkel Ferenc?','2'),
('Melyik királyról nem írt drámát William Shakespeare?','2'),
('Hol játszódik a Szentivánéji álom Shakespeare vígjátéka?','2'),
('Mi volt a foglalkozása az íráson kívül Örkény Istvánnak?','2'),
('Hogy hívták Harry édesapját a Harry Potter c. regénysorozatban?','2'),
('Milyen mágus Sirius Black Harry keresztapja?','2'),
('Ki írta az Abigél c. regényt?','2'),
('Melyik író Kosztolányi Dezső unokatesvére?','2'),
('Mi Csáth Géza eredeti neve?','2'),
('Mikor alakult a Kisfaludy Társaság?','2'),
('Milyen Nobel-díjat kapott az idén Bob Dylan?','2'),
('Milyen nemzetiségű volt Alfred Nobel?','2'),
('Kik kapják a Pulitzer-díjat?','2'),
('Hol született Paulo Coelho író?','2'),
('Ki Dumbledore a Harry Potter c. regényben?','2'),
('Mi a neve Harry barátnőjének a Harry Potterben?','2'),
('Kinek a műve "A funtineli boszorkány"?','2'),
('Kinek a műve az Egyperces novellák?','2'),
('Melyik király léptet fakó lován Arany balladájában?','2'),
('Hol halt meg Wass Albert erdélyi magyar író?','2'),
('Kinek a műve a Pál utcai fiúk c. regény?','2'),
('Ki írta az Abigélt?','2'),
('Ki nem kapott Nobel-békedíjat?','2'),
('Ki Gina osztályfőnöke az Abigél c. regényben?','2'),
('Ki a főszereplője a Légy jó mindhalálig c. regénynek?','2'),
('Melyik nem Jules Verne műve?','2'),
('Melyik országban játszódik "A nyomorultak" c. regény cselekménye?','2'),
('Ki volt Gombaszögi Ella?','2'),
('Melyik kontinens legdélebbi pontja a Horn-fok?','2'),
('Melyik író alkotása a Beszterce ostroma c. regény?','2'),
('Kinek a műve az Anna Karenina?','2'),
('Melyik regényben szerepel Öreg Názó?','2'),
('Mi a neve az internátusnak az Abigél c. regényben?','2'),
('Kinek olvas fel Nyilas Misi a Légy jó mindhalálig c. regényben?','2'),
('Melyik regényben szerepel Szentirmay Katinka?','2'),
('Kinek a műve a Kárpáthy Zoltán?','2'),
('Kinek a regénye az Árvácska?','2'),
('Kinek a regénye "A Mester és Margarita"?','2'),
('Melyik műben szerepel Kutuzov herceg?','2'),
('Melyik városban játszódik Az ember tragédiája VI. színe?','2'),
('Kinek a regénye az Aranykoporsó?','2'),
('Melyik városban hunyt el Móra Ferenc?','2'),
('Kinek a műve a Csongor és Tünde?','2'),
('Melyik regényben szerepel Mimó néni?','2'),
('Melyik regény szereplője Bicebóca?','2'),
('Milyen iskolában játszódik Ottlik Géza: Iskola a határon c. műve?','2'),
('Melyik regényben szerepel Kacsuka Imre?','2'),
('Mi a neve a Kincskereső kisködmön c. regény főhősének?','2'),
('Kinek a műve a Harmat és vér c. novella?','2'),
('Mi volt Gárdonyi Géza eredeti családneve?','2'),
('Melyik regényben szerepel Balogh Csaba festő?','2'),
('Melyik Gárdonyi regényben szerepelt Jumurdzsák?','2'),
('Mi a neve "A láthatatlan ember" c. regény főszereplőjének?','2'),
('Kinek a műve a Búzavirágok és kalászok?','2'),
('Hol született Mikszáth Kálmán?','2'),
('Melyik mű szereplője Egérkirály?','2'),
('Melyik költőnk verse a Szeptember végén?','2'),
('Mi volt Petőfi Sándor édesapjának foglalkozása?','2'),
('Melyik város kollégiumában játszódik a Légy jó mindhalálig c. regény?','2'),
('Mi volt Gergő apjának foglalkozása a Kincskereső kisködmön c. regényben?','2'),
('Kinek a regénye a Hannibál tanár úr?','2'),
('Melyik regény szereplője Zsabapolka?','2'),
('Ki írta "A koppányi aga testamentuma" c. regényt?','2'),
('Melyik regény folytatása volt a Téli berek?','2'),
('Ki írta a Jadvida párnája c. regényt?','2'),
('Melyik regény szereplője Pondoray Béla?','2'),
('Kinek a regénye az Utas és holdvilág?','2'),
('Melyik mű szereplője Biberach?','2'),
('Kinek a kötete volt a Zuzmara a rózsafán?','2'),
('Kinek a regénye a Gergő és az álomfogók?','2'),
('Hogy hívták János vitéz szerelmét?','2'),
('Kinek a műve a Galamb és béka?','2'),
('Mi az alcíme a Beszterce ostroma c. Mikszáth regénynek?','2'),
('Melyik regény szereplője Bátky János?','2'),
('Hány éves korában kezdett verseket írni Petőfi Sándor?','2'),
('Melyik irodalmi mű szereplője Csicsó?','2'),
('Mi Mark Twain eredeti keresztneve?','2'),
('Kinek a kötete volt a Csutak és a szürke ló?','2'),
('Kinek a regénye "Az öreg halász és a tenger"?','2'),
('Melyik költő verse a Száncsengő?','2'),
('Milyen csillag állt felettünk József Attila: Betlehemi királyok c. versében?','2'),
('Melyik az Újszövetség első könyve?','2'),
('Kinek a műve " A katedrális"?','2'),
('Kinek a regénye "A fekete kolostor"?','2'),
('Melyik költő verse az Újévi köszöntő?','2'),
('Melyik regény szereplője Torma Gedeon?','2'),
('Mi volt Fekete István első regénye?','2'),
('Melyik a Harry Potter regénysorozat első könyve?','2'),
('Ki a Harry Potter sorozat főgonosza?','2'),
('Ki játssza az irodalomtanárt a "Holt költők társasága" c. filmben?','2'),
('Melyk író álneve volt a P.Howard?','2'),
('Hány karátos autó szerepel Rejtő Jenő művének címében?','2'),
('Kinek a műve a Zsivago doktor?','2'),
('Ki nem Rejtő Jenő műveiben szerepel?','2'),
('Kinek a műve a Pendragon legenda?','2'),
('Melyik francia költő verse az Őszi chanson?','2'),
('Melyik Shakespeare dráma szereplője Orsino herceg?Vízkereszt','2'),
('Ki írta a Szent Péter esernyője c. regényt?','2'),
('Hol játszódik "Az ember tragédiájának" V. színe?','2'),
('Melyik volt Stephen King első 1974-ben megjelent regénye?','2'),
('Kinek a műve "A 6-os számú kórterem"?','2'),
('Melyik regény főszereplője Tábory Elemér?','2'),
('Melyik amerikai író műve az "Otthon édes otthon"?','2'),
('Melyik író műve az "Így szerettek ők"?','2'),
('Mi volt "A Pendragon legenda" Szerb Antal regényének eredeti címe?','2'),
('Mi az alliteráció?','2'),
('Milyen fajtájú kutya Bogáncs Fekete István regényében?','2'),
('Kinek a regénye a Macska a galambok között?','2'),
('Mi a Kalevala?','2'),
('Kinek a regénye a Goriot apó?','2'),
('Kinek a regénye a "A rettegés arénája"?','2'),
('Milyen sportot nem űzött Ernest Hemingway amerikai író?','2'),
('Mi volt a Richard Sharpe-regények első kötete?','2'),
('Mi volt Fejős Éva író első műve?','2'),
('Kinek a regénye az 1984?','2'),
('Kinek a regénye "A párizsi Notre-Dame"?','2'),
('Hány tagja van a Gyűrű szövetségének "A Gyűrűk urai" c. regényben?','2'),
('Ki írta Für Elise c. regényt?','2'),
('Hol született Petőfi Sándor?','2'),
('Ki Thomas Mann "A varázshegy" c. regényének főhőse?','2'),
('Mi az eposz?','2'),
('Melyik együttes dolgozta fel Radnóti Miklós:Bájoló c. versét?','2'),
('Milyen nemzetiségű Stieg Larsson író?','2'),
('Ki a főszeplője az " Indul a bakterház" c. regénynek?','2'),
('Hogy folytatódik a nyelvtörő? "Fekete bikapata kopog......"','2'),
('Kinek a regénye a "Büszkeség és balítélet"?','2'),
('Mi volt Charles Dickens első regénye?','2'),
('Hány kötetből áll J. F. Cooper Nagy Indiánkönyve?','2'),
('Melyik amerikai író műve a Macska a forró bádogtetőn?','2'),
('Mikor született József Attila?','2'),
('Hogy folytatódik József Attila verse? "Nincsen apám se anyám','2'),
('Milyen állat nem volt "A brémai muzsikusok" között?','2'),
('Mi a neve az erdőnek ahol Micimackó élt?','2'),
('Melyik Shakespeare dráma szereplői Claudius és Ophelia?','2'),
('Ki volt a Pál utcai fiúk c. regényben az áruló?','2'),
('Milyen labdajátékot űz Harry Potter?','2'),
('Kinek a műve "A Szent Johanna gimi" sorozat?','2'),
('Ki Kosztolányi Dezső unokatesvére?','2'),
('Hány kőműves építette Déva várát a népballadában?','2'),
('Melyik nem Paulo Coelho műve?','2'),
('Kinek a regénye a Szegény gazdagok és a Fekete gyémántok?','2'),
('Milyen állata volt Harry Potternek?','2'),
('Kinek a regénye "A Gyűrűk Ura"?','2'),
('Mi volt Harry Potter első kötetének a címe?','2'),
('Kinek a műve a Tartuffe?','2'),
('Melyik költő verse a Héja-nász az avaron?','2'),
('Hány évet töltött Robinson Crusoe egy szigeten?','2'),
('Hány köteltből áll a Twilight (Alkonyat) c. fantasyregény?','2'),
('Melyik írónk született Érdmindszenten?','2'),
('Kinek a drámája az Éjjeli menedékhely?','2'),
('Melyk író álneve volt P.Howard?','2'),
('Ki Grecsó Krisztián?','2'),
('Kinek a műve "A 6-os számú kórterem"?','2'),
('Hány karátos autó szerepel Rejtő Jenő művének címében?','2'),
('Mi a Douglas Adams regény címének befejezése? "Galaxis útikalauz...."','2'),
('Kinek a regénye "Az öreg halász és a tenger"?','2'),
('Melyik regény főszereplője Tábory Elemér?','2'),
('Kinek a műve a Pendragon legenda?','2'),
('Mi volt "A Pendragon legenda" Szerb Antal regényének eredeti címe?','2'),
('Ki irta a "A walesi bárdok" c. verset?','2'),
('Hol született Paulo Coelho író?','2'),
('Hol született Arany János?','2'),
('Kinek a műve a Kárpáthy Zoltán?','2'),
('Melyik nem William Shakespeare drámája?Doctor Faustus','2'),
('Melyik francia író műve "A párizsi Notre-Dame"?','2'),
('Milyen szelek a címe Emily Bronte regényének?','2'),
('Ki írt könyvet a Rolling Stones zenekarról?','2'),
('Melyik író regényei a "Beszterce ostroma" és "A fekete város"?','2'),
('Melyik Rejtő Jenő hős mondta:" Uram! A késemért jöttem!"?','2'),
('Melyik költő verse a "Kis karácsonyi ének"?','2'),
('Ki írta a Holt Vidék c. verset?','2'),
('Mi volt a Harry Potter első kötetének a címe?','2'),
('Milyen állat szerepel "A kis herceg"c. regényben?','2'),
('Mikor született Petőfi Sándor?','2'),
('Ki írt Mary Westmacott álnéven?','2'),
('Csehov melyik művében szerepel Arkagyina?','2'),
('Melyik író műve az "Egyperces novellák"?','2'),
('Mi a görög abc utolsó betűje?','2'),
('Ki írta a "Kaukázusi krétakör" c. drámát?','2'),
('Hány süntestvér volt Csukás István "Sün Balázs" c. versében?','2'),
('Mi volt Lédának Ady Endre múzsájának a születéskori neve?','2'),
('Mikor született Zsákos Frodó "A Gyűrűk Ura" c. regényben?','2'),
('Kinek a költeményei voltak a Iliasz és az Odüsszeia?','2'),
('Mikor írta Kölcsey Ferenc a Himnuszt?','2'),
('Milyen nemzetiségű volt Andersen a meseíró?','2'),
('Ki kapta 2018-ban a Kölcsey-emlékpakettet a magyar kultúra napjának alkalmából?','2'),
('Milyen regények szerzője Mary Higgins Clark?','2'),
('Melyik író műve " A félkegyelmű"?','2'),
('Mi volt József Attila édesanyjának a foglalkozása?','2'),
('Ki tervezte a Kölcsey-emlékplakettet?','2'),
('Milyen állat őrzi az álmát Bóbitának Weöres Sándor versében?','2'),
('Mikor volt István királlyá koronázása?','3'),
('Mikor volt a kenyérmezei csata?','3'),
('Kik voltak a Küklopszok a görög mitológiában?','3'),
('Ki volt a második honalapító?','3'),
('Ki volt Az árvízi hajós?','3'),
('Ki fedezte fel a déli sarkkört?','3'),
('Mikortól lehet Magyarországon öttöslottóval játszani?','3'),
('Mikor alapították a Pannonhalmi apátságot?','3'),
('1995-ben ki volt az USA elnöke?','3'),
('Ki volt Hunyadi Mátyás anyja?','3'),
('Kik voltak a tatárok?','3'),
('Ki volt Dzsingisz kán?','3'),
('Hol dolgozott a molnár?','3'),
('Mióta Barack Obama az USA elnöke?','3'),
('Ki volt Orpheusz felesége?','3'),
('Melyik háborúban volt a Barbadossa hadművelet?','3'),
('Ki volt Szókratész?','3'),
('Mikor gyártották az első Trabantot?','3'),
('Ki volt Rózsa Sándor?','3'),
('Ki az uralkodó Spanyolországban?','3'),
('Ki látható az 1000 Ft-os bankjegyen?','3'),
('Mikor vezették be a forintot Magyarországon?','3'),
('Mikor indult meg az első pesti lóvasút?','3'),
('Ki volt az USA első elnöke?','3'),
('Mi volt a ragadványneve Mátyás királynak?','3'),
('Melyik régi bankjegyen volt látható Kossuth Lajos?','3'),
('Ki volt a kalapos király?','3'),
('Mi volt Szombahely ókori latin neve?','3'),
('Mikor volt a mohácsi csata?','3'),
('Hol mutatták be először Az Operaház fantomja c. musicalt?','3'),
('Melyik vár kapitánya volt Dobó István?','3'),
('Mikor nyílt meg a Népstadion Budapesten?','3'),
('Hol őrzik a Szent Jobbot?','3'),
('Milyen magas a Szent István-bazilika?','3'),
('Ki volt Szent István király felesége?','3'),
('Melyik nem a koronázási jelvények közé tartozik?','3'),
('Melyik fejedelmünk anyja Zrínyi Ilona?','3'),
('Ki az uralkodó az Egyesült Királyságban?','3'),
('Hány gyermeke született Károly Walesi hercegnek?','3'),
('Ki volt Oliver Cromwell?','3'),
('Mikor vezették be az eurót?','3'),
('Melyik amerikai állam kormányzója Arnold Schwarzenegger?','3'),
('Mi volt Sisi császárnő teljes neve?','3'),
('Hol látható a Grassalkovich-kastély?','3'),
('Mi volt a régi Inka Birodalom központja?','3'),
('Ki Dánia(Dán királyság)uralkodója?','3'),
('Az Assisi Szent Ferenc-bazilikát mikor nyílvánították a Világörökség részévé?','3'),
('Ádám melyik csontjából lett Éva?','3'),
('Hány felesége volt VIII. Henrik angol királynak?','3'),
('Hanyadik felesége volt VIII. Henriknek Boleyn Anna?','3'),
('Mi történt VIII. Henrik harmadik feleségével?','3'),
('Ki lépte át először a déli sarkkört?','3'),
('Ki követte I. István magyar királyt a trónon?','3'),
('Melyik királyunk nevéhez fűződik az Aranybulla kiadása?','3'),
('Mikor volt a tatárjárás?','3'),
('Ki volt az utolsó magyar király?','3'),
('Ki volt Mária Terézia fia?','3'),
('Hány évig uralkodott I. Ferenc József?','3'),
('Ki volt Thököly Imre házastársa?','3'),
('Ki volt Tomori Pál?','3'),
('Ki nem a hét honfoglaló vezér egyike?','3'),
('Melyik ország királynéja volt Stuart Mária?','3'),
('Mikor kezdte meg a Magyar Rádió az adását?','3'),
('Ki volt az első felelős magyar kormány igazságügyminisztere?','3'),
('Hány aradi vértanu volt?','3'),
('Ki Magyarország köztársasági elnöke jelenleg?','3'),
('Melyik országban zajlott a rózsák háborúja?','3'),
('Mikor volt a lepantói csata?','3'),
('Hány táblából áll a Gyönyörök kertje c. műalkotás?','3'),
('Milyen színű a híres delfti fajansz?','3'),
('Ki a pszihoanalitikus iskola megalapítója?','3'),
('Ki volt az evolúcióelmélet kidolgozója?','3'),
('Ki van az amerikai 100 dolláros bankjegyen?','3'),
('Mikor kezdődött pontosan az 1956-os forradalom?','3'),
('Mikor volt a körmendi csata?','3'),
('Ki volt az első magyar enciklopédista?','3'),
('Mi a neve annak a fegyvernek amivel Jézust megsebezték a kereszten?','3'),
('Mikor hozták létre a Magyar Örökség díjat?','3'),
('Mi volt Vak Bottyán igazi neve?','3'),
('Mi volt a neve Odüsszeusz feleségének?','3'),
('Ki volt a szépség és a szerelem istennője a görög mitológiában?','3'),
('Kik voltak a gigászok a görög mitológiában?','3'),
('Kinek az ikertestvére volt Artemisz?','3'),
('Mi volt Madách Imre fő műve?','3'),
('Melyik évben kiáltották ki a köztársaságot Magyarországon?','3'),
('Ki volt az 56-os forradalom alatt a Miniszertanács elnöke?','3'),
('Mi volt Kádár János születéskori neve?','3'),
('Mit tart Atlasz a vállán a görög mitológiában?','3'),
('Mikor volt a váradi békekötés?','3'),
('Ki volt II. Rákóczi György?','3'),
('Mikor volt a Challenger-katasztrófa?','3'),
('Ki jelenleg Budapest főpolgármestere?','3'),
('Ki volt Zolta a magyar történelemben?','3'),
('Ki követte II. Andrást a trónon?','3'),
('Ki volt II. Civakodó Frigyes?','3'),
('Kik találták fel a mozit?','3'),
('Mikor hozták létre a párizsi Disneyland-et?','3'),
('Milyen származású Kolumbusz Kristóf?','3'),
('Mi volt a neve Kolumbusz vezérhajójának?','3'),
('Mi a squash?','3'),
('Hány felesége volt Julius Caesarnak?','3'),
('Melyik amerikai bankjegy hátoldalán látható a Fehér-ház?','3'),
('Melyik ország nemzeti hőse volt Tell Vilmos?','3'),
('Hány évesen halt meg Bornemissza Gergely?','3'),
('Mikor volt a bostoni teadélután?','3'),
('Melyik ország ellen vívták az amerikai függetlenségi háborút?','3'),
('Ki volt "Az árvízi hajós"?','3'),
('Mikor van a forint bevezetésének napja?','3'),
('Hány tudós nevét örökítettek meg az Eiffel-tornyon?','3'),
('Mikor adták át a Kisföldalatti Vasutat?','3'),
('Mi a neve Erdélyben a répának?','3'),
('Ki volt Benyovszki Móric?','3'),
('Melyik ország elnöke volt Nelson Mandela?','3'),
('Melyik királyunk lánya volt Árpád-házi Szent Margit?','3'),
('Ki volt Aba Sámuel?','3'),
('Ki Bill Gates?','3'),
('Mi maradt benn Pandora szelencéjében a görög mitológia szerint?','3'),
('Hány gyermeke van II. Erzsébet brit királynőnek?','3'),
('Melyik két csapat között zajlott a verduni csata?','3'),
('Mikor alapították Herendi Porcelánmanufaktúrát?','3'),
('Mikor írták alá a trianoni békeszerződést?','3'),
('Ki volt Sisi osztrák császárné édesapja?','3'),
('Ki volt Borromeo Szent Károly?','3'),
('Ki volt Hitvalló Eduárd?','3'),
('Ki volt a ferences rend megalapítója?','3'),
('Kinek a lánya volt Árpád-házi Szent Erzsébet?','3'),
('Ki volt az első magyar régésznő?','3'),
('Ki volt Canterburyi Szent Tamás?','3'),
('Ki nem tartozik a négy evangelista apostolok közé?','3'),
('Ki volt Széchenyi István édesanyja?','3'),
('Hány évig szolgáltatott áramot az Inotai hőerőmű?','3'),
('Mi volt Vasvári Pál eredeti neve?','3'),
('Kik voltak a vandálok?','3'),
('Mikor indult útjára a cserkészmozgalom Magyarországon?','3'),
('Hány feleségét fejeztetett le VIII. Henrik angol király?','3'),
('Ki 2013-tól a római pápa?','3'),
('Mit készített a takács?','3'),
('Hány szakaszból állt az angol polgári forradalom?','3'),
('Melyik uralkodónk latin neve volt Mathias Rex?','3'),
('Mikor volt a Casablancai konferencia?','3'),
('Mi volt Ausztria az euró bevezetése előtti pénzneme?','3'),
('Melyik kor előzte meg az ókort?','3'),
('Ki volt a magyar jakobinus mozgalom vezére?','3'),
('Ki volt az első római császár?','3'),
('Milyen hosszú a La Manche csatorna?','3'),
('Melyik évben kezdődött a kaliforniai aranyláz?','3'),
('Ki Hollandia jelenlegi királya?','3'),
('Ki volt Barack Obama elődje az amerikai elnöki székben?','3'),
('Kik nem léphetnek be az Athosz-hegyi Köztársaság területére?','3'),
('Melyik ország adta a Szabadság-szobrot az USA-nak?','3'),
('Mikor volt a nagy gazdasági világválság?','3'),
('Hol született Széchenyi István?','3'),
('Mikor volt István királlyá koronázása?','3'),
('Mikor volt a kenyérmezei csata?','3'),
(' Mikor volt a nikolsburgi békeszerződés?','3'),
(' Hány európai ország kapott segélyt a Marshall-terv nemzetközi segélyprogram keretében?','3'),
(' Mikor vezette be a Magyar Posta az irányítószámok használatát?','3'),
(' Ki kapta 1979-ben a Nobel-békedíjat?','3'),
(' Milyen nemzetiségű volt Marco Polo?','3'),
(' Melyik háborút zárta le a hubertusburgi béke?','3'),
(' Hány évig tartott valójában a százéves háború?','3'),
(' Melyik évben csatlakozott Magyarország az Európai Unióhoz?','3'),
(' Mikor volt a soproni népszavazás?','3'),
(' Milyen rokoni kapcsolatban állt Zeusszal Artemisz?','3'),
(' Ki követte IV. Bélát a magyar trónon?','3'),
(' Hány gyermeke született Mária Teréziának?','3'),
(' Hány évig uralkodott Viktória királynő?','3'),
(' Hol született Bonaparte Napóleon?','3'),
(' Melyik évben volt a nagy londoni tűzvész?','3'),
(' Mit készítettek a bodnárok?','3'),
(' Hol halt meg Bartók Béla?','3'),
(' Mikor kötötték a Szent Szövetséget?','3'),
(' Mikor vonták ki a forgalomból Magyarországon az 1 és 2 forintos érméket?','3'),
(' Árpád után ki volt a következő Árpád-házi fejedelem?','3'),
(' Hanyadik elnöke volt az USA-nak John Fitzgerald Kennedy?','3'),
(' Mikor nyitották meg a Nyugati pályaudvart?','3'),
(' Hány múzsa volt a görög mitológiában?','3'),
(' Mikor nyitotta meg kaput a párizsi Disneyland?','3'),
(' Mettől-meddig tartott az 1848–49-es forradalom és szabadságharc?','3'),
(' Mikor vívták a pákozdi csatát?','3'),
(' Az 1848-as forradalom hanyadik évfordulóján adtak át először Kossuth-díjat?','3'),
(' Hány cm magas a Batthyány-örökmécses?','3'),
(' Ki volt „a haza bölcse” és „a nemzet prókátora” ?','3'),
(' Kik a számik?','3'),
(' Mi volt Fa Nándor első hajójának a neve?','3'),
(' Mikor alapították a Magyar Vöröskeresztet?','3'),
(' Kiknek a nemzeti viselete a kimonó?','3'),
(' Mikor szűnt meg a Budapesti Vidám Park?','3'),
(' Mióta létezik Magyarországon televízió?','3'),
(' Melyik amerikai elnök lemondásához vezetett a Watergate-botrány?','3'),
(' Mi az ENSZ székhelye?','3'),
(' Mettől-meddig tartott a sztálingrádi csata?','3'),
(' Hány tanítványa (apostola) volt Jézusnak?','3'),
(' Hány ország tagja az ENSZ-nek?','3'),
(' Kik voltak a komancsok?','3'),
(' Hány évig uralkodott Viktória királynő?','3'),
(' Melyik évben volt a kenyérmezei csata?','3'),
(' Hol született Jézus Krisztus?','3'),
(' Melyik bankjegyen látható Mátyás király?','3'),
(' Hogy hívták I. Szulejmán hitvesét?','3'),
(' Ki volt I. Szent László apja?','3'),
(' Ki az uralkodó Dániában?','3'),
(' Mikből állnak a Seuso-kincsek?','3'),
(' Mettől-meddig tartott az angol polgári forradalom?','3'),
(' Mikor volt a szatmári békekötés?','3'),
(' Hol őrzik "Lehel kürtjét" ?','3'),
(' Melyik királyt tartják Budavár alapítójának?','3'),
(' Ki volt Szent Flórián?','3'),
(' Melyik országból származik a szauna?','3'),
(' Mikor nyílt meg a Ferihegyi Nemzetközi Repülőtér?','3'),
(' Mikor volt a thermopülai csata?','3'),
(' Melyik háború az alapja a Miss Saigon c. musicalnek?','3'),
(' Ki alapította a tihanyi apátságot?','3'),
(' Hol halt meg II. Rákóczi Ferenc?','3'),
(' Melyik országból származik a Szamba tánc?','3'),
(' Jelenleg ki a norvég király?','3'),
(' Melyik évben nyitotta meg kapuit a Groupama Aréna?','3'),
(' Ki az uralkodó az Egyesült Királyságban?','3'),
(' Mikor vezették be az eurót?','3'),
(' Hány évig tartott valójában a százéves háború?','3'),
(' Mikor volt István királlyá koronázása?','3'),
(' Melyik fejedelem anyja Zrínyi Ilona?','3'),
(' Melyik volt hazánk első nemzeti parkja?','3'),
(' Ki követte IV. Bélát a magyar trónon?','3'),
(' Hány évig uralkodott Viktória királynő?','3'),
(' Mikor ütközött egy jéghegynek a Titanic?','3'),
(' Mikor volt a Morvamezei-csata?','3'),
(' Ki volt I. Leonidasz?','3'),
(' Hány festményt loptak el 1983-ban a Szépművészeti Múzeumból?','3'),
(' Ki volt a "haza bölcse"?','3'),
(' Melyik egy fáraó?','3'),
(' Melyik város védőszentje Szent Miklós?','3'),
(' Mikor volt a Pearl Harbor-i csata?','3'),
(' Ki volt I.(Szent)István király édesapja?','3'),
(' Melyik ország elnöke volt Nelson Mandela?','3'),
(' Melyik évben égett le a Budapest Sportcsarnok?','3'),
(' Hanyadik évezred van most?','3'),
(' Ki volt Zeusz apja a görög mitológiában?','3'),
(' Miről kapta nevét a Wartburg autó?','3'),
(' Ki avatta fel a Sydney-i Operaházat?','3'),
(' Mikor volt a bostoni teadélután?','3'),
(' Mit készítettek a kádárok?','3'),
(' Mikor omlott le a berlini fal?','3');

INSERT INTO [dbo].[Question]
           ([QuestionText]
           ,[CategoryFK])
     VALUES	 
(' Mikor jött létre az ENSZ?','3'),
(' Ki jelenleg Magyarország köztársasági elnöke?','3'),
(' Mikor volt az egri vár ostroma?','3'),
(' Ki volt Bonaparte Napoleon házastársa?','3'),
(' Ki volt Izsák apja a Bibliában?','3'),
(' Melyik nem tartozik a világ hét új csodája közé?','3'),
(' Melyik király alapította a tihanyi apátságot?','3'),
(' Mikor adták ki az Aranybullát?','3'),
(' Ki volt az orvostudomány megalapítója?','3'),
(' Alföldi Róbert melyik színház igazgatója volt 2008-tól-2013-ig?','3'),
(' Ki volt Széchenyi István édesanyja?','3'),
(' Mikor vezették be az eurót?','3'),
(' Mikor készítették az első Trabantot?','3'),
(' Hanyadik századig tartott a középkor?','3'),
(' Melyik ország nem tartozik a visegrádi négyek közé?','3'),
(' Minek a rövidítése a NATO?','3'),
(' Melyik nem világörökségi helyszín?','3'),
(' Mit jelent a GDP magyarul?','3'),
(' Ki követte II. Andrást a trónon?','3'),
(' Kik voltak a normannok?','3'),
(' Mi volt Mária Terézia uralkodói neve?','3'),
(' Mikor futott zátonyra a Costa Concordia hajó?','3'),
(' Hány évig tartott az első világháború?','3'),
(' Melyik épitmény került be a világ hét új csodája közé?','3'),
(' Melyik budapesti szigeten hunyt el Árpád-házi Szent Margit?Válaszok: Margit-szigeten','4'),
('Mi Magyarország második legnagyobb tava?','4'),
('Mi Nógrád megye székhelye?','4'),
('Hozzávetőlegesen mennyi a Föld népessége?','4'),
('Melyik ország fővárosa Dublin?','4'),
('Hány km a távolság Szolnok és Budapest között?','4'),
('Melyik államban van Dallas?','4'),
('Hol található Budapesten a Halászbástya?','4'),
('Melyik város nevezetessége a Big Ben?','4'),
('Melyik Magyarországi megyében van Sásd?','4'),
('Honnan ered a Duna?','4'),
('Mi Litvánia fővárosa?','4'),
('Honnan indul a Balaton átúszás?','4'),
('Mi Kalifornia állam székhelye?','4'),
('Melyik a Föld leghosszabb folyója?','4'),
('Melyik nem tartozik a világ hét csodája közé?','4'),
('Mikor volt a Morvamezei-csata?','4'),
('Hány km-re van egymástól Tatabánya és Nyíregyháza?','4'),
('Melyik magyar város nevezetessége a Dzsámi?','4'),
('Mi Norvégia fővárosa?','4'),
('Mi volt az Aranybulla?','4'),
('Melyik megyében van Csanádapáca?','4'),
('Hány m magas a Kékes?','4'),
('Mikor volt a Nyugatrómai Birodalom bukása?','4'),
('Mi Bulgária fővárosa?','4'),
('Melyik magyar város jelképe a Tűztorony?','4'),
('Melyik nem szikes tó?','4'),
('Hol van Bora Bora szigete?','4'),
('Milyen az éghajlata Caracasnak?','4'),
('Melyik óceánban vannak a Seychelle-szigetek?','4'),
('Hány szövetségi államból áll az USA?','4'),
('Melyik ország fővárosa Maputo?','4'),
('Mi Kanada államformája?','4'),
('Hol torkollik a Tiszába a Maros?','4'),
('Hány megyéből áll Magyarország?','4'),
('A Föld felszínének hány %-át foglalja el az Atlanti-óceán?','4'),
('Melyik ország fővárosa Hanoi?','4'),
('Mekkora a Balaton legnagyobb mélysége?','4'),
('Milyen hosszú a Velencei-tó?','4'),
('Hol van a Golden Gate híd?','4'),
('Mennyi Zalaegerszeg és Budapest távolsága?','4'),
('Lillafüred melyik város része?','4'),
('Denver melyik amerikai állam székhelye?','4'),
('Melyik téren van Budapesten a Mátyás templom?','4'),
('Melyik a világ legnagyobb kávétermelő országa?','4'),
('Hol van Tasmania szigete?','4'),
('Melyik fővárosban látható a Petronas-ikertorony?','4'),
('Mi a neve a keszthelyi kastélynak?','4'),
('Mi a Csomolungma hegy másik elnevezése?','4'),
('Hány méter magas a Csomolungma?','4'),
('Mikor született I. Napoleon császár?','4'),
('Hol van Machu Picchu az egykori Inka Birodalom romvárosa?','4'),
('Mit jelent magyarul Buenos Aires?','4'),
('Ki volt Álmos fejedelem fia?','4'),
('Mit a jelent a Mont Blanc?','4'),
('Hány m magas a Pilis?','4'),
('Mi Komárom-Esztergom megye székhelye?','4'),
('Milyen magas a Kőris-hegy?','4'),
('Mi Rio de Janeiro jelentése?','4'),
('Melyik megyében van Kőszeg?','4'),
('Heves-megyében hány város található?','4'),
('Milyen hosszú a Mississippi folyó?','4'),
('Mi Kanada fővárosa?','4'),
('Melyik ország felé fúj a Bóra szél?','4'),
('Melyik országon nem folyik keresztül az Amazonas folyó?','4'),
('Melyik tó nem az amerikai Nagy-tavak közé tartozik?','4'),
('Milyen hosszú a Michigan-tó?','4'),
('Melyik város polgármestere Borkai Zsolt olimpiai bajnok tornász?','4'),
('Mi Uruguay fővárosa?','4'),
('Milyen széles a Gibraltári-szoros?','4'),
('Melyik az Európai Unió legkisebb tagállama?','4'),
('Melyik Győr legjelentősebb folyója?','4'),
('Kik ellen harcoltak a magyarok a Muhi csatában?','4'),
('Milyen építészeti stílusban épült a Magyar Állami Operaház?','4'),
('Ki jelenleg Svédország királya?','4'),
('Mennyi a legnagyobb mélysége az Atlanti-óceánnak?','4'),
('Melyik városban rendezik a Virágkarnevált?','4'),
('Melyik országon nem halad keresztül a Duna?','4'),
('Melyik megyénkben található Dunapataj?','4'),
('Melyik város volt 2009-ben az Év Települése?','4'),
('Melyik folyó szeli ketté Csongrád megyét?','4'),
('Mi Csongrád megye legdélibb települése?','4'),
('Melyik megyében van Siófok?','4'),
('Milyen hosszú a Sió-csatorna?','4'),
('Mi Esztergom partnervárosa?','4'),
('Melyik Nemzeti Park része a Káli-medence?','4'),
('Melyik volt hazánk első nemzeti parkja?','4'),
('Mikor alapították az Őrségi Nemzeti Parkot?','4'),
('Ki a Dunakanyar védőszentje?','4'),
('Melyik országban van Havasalföld?','4'),
('Melyik folyó Magyarország és Horvátország határfolyója?','4'),
('Melyik tengerben fekszik Jamaica?','4'),
('Melyik tenger nem tartozik a Hét tenger közé?','4'),
('Melyik országban van a Márvány-tenger?','4'),
('Mi Montenegro fővárosa?','4'),
('Melyik amerikai város része Hollywood?','4'),
('Melyik amerikai államban van a Grand Canyon?','4'),
('Mi a Grand Canyon jelentése?','4'),
('Mettől-meddig tartott az első világháború?','4'),
('Melyik országban van Montreal?','4'),
('Melyik ország szigete Szicília?','4'),
('Mi San Marino hivatalos nyelve?','4'),
('Melyik nem vulkán?','4'),
('Mi Malayzia fővárosa?','4'),
('Melyik országban van Casablanca?','4'),
('Mi Győr-Moson-Sopron megye székhelye?','4'),
('Melyik várost nevezik a nyugat királynőjének?','4'),
('Kőszeg várát ki védte 1532-ben?','4'),
('Hány km-re van Debrecentől Hajdúszoboszló?','4'),
('Mikor jött létre a Hortobágyi Nemzeti Park?','4'),
('Melyik város az UNESCO központja?','4'),
('Mi a Baktérítő?','4'),
('Melyik a Föld leghosszabb szélességi köre?','4'),
('Melyik országon nem halad keresztül az Egyenlítő?','4'),
('Melyik kontinenshez tartozik Egyenlítői-Guinea?','4'),
('Melyik országhoz tartoznak a Galápagos-szigetek?','4'),
('Hány nagyobb szigetből állnak a Galápagos-szigetek?','4'),
('Hol van a Titicaca-tó?','4'),
('Hányszor nagyobb a Balatonnál a Titicaca-tó?','4'),
('Melyik a világ legmagasabban fekvő városa?','4'),
('Mi Portugália egyetlen szomszédja?','4'),
('Mi választja el Spanyolországot Marokkótól?','4'),
('Hány km széles a Gibraltári-szoros?','4'),
('Miként emlegetik Finnországot?','4'),
('Melyik ország megyéje Finnmark?','4'),
('Melyik tenger mellett fekszik Lettország?','4'),
('Melyik ország városa Krakkó?','4'),
('Mi Szlovákia fővárosa?','4'),
('Hol látható a Sixtus-kápolna?','4'),
('Melyik a Föld leghosszabb hegysége?','4'),
('Hol található a Tien-San hegység?','4'),
('Mi a neve a Sziklás-hegység legmagasabb csúcsának?','4'),
('Melyik földrész hegylánca az Alpok?','4'),
('Melyik országban van a Yellowstone Nemzeti Park?','4'),
('Melyik Európa legnagyobb vulkánja?','4'),
('Melyik megyében van Hollókő?','4'),
('Melyik hegy tetején van a Citadella?','4'),
('Mi a gleccser?','4'),
('Mi a Budai-hegység legmagasabb pontja?','4'),
('Hány méter magas a János-hegy?','4'),
('Mi a Normafa régi neve?','4'),
('Hanyadik kerületben van a Rózsadomb Budapesten?','4'),
('Melyik a Föld legnagyobb szigete?','4'),
('Melyik országban található Szumátra szigete?','4'),
('Mi Nepál fővárosa?','4'),
('Melyik félszigeten fekszik Egyiptom?','4'),
('Melyik a Föld legnagyobb sivataga?','4'),
('Hány piramisból állnak a Gízai piramisok?','4'),
('A gízai nagy Szfinx milyen testű lényt ábrázol?','4'),
('Labrador félszigete melyik országban van?','4'),
('Melyik óceánban helyezkedik el Kamcsatka?','4'),
('Mi az Andok legmagasabb pontja?','4'),
('Melyik országot nevezték el Jézus Krisztusról?','4'),
('Hány ország található a Nagy-Antillák szigetein?','4'),
('Melyik kontinens partjainál van a Nagy-korallzátony?','4'),
('Mi Baranya megye székhelye?','4'),
('Melyik megyében van Hatvan?','4'),
('Hol látható a Deseda-tó?','4'),
('Hol található az Amazonas-medence?','4'),
('Mi Haiti egyetlen szárazföldi szomszédja?','4'),
('Melyik zene őshazája Jamaica?','4'),
('Mi Kolumbia hivatalos nyelve?','4'),
('Milyen hosszú az Orinoco folyó Dél-Amerikában?','4'),
('Mi Ciprus fővárosa?','4'),
('Mi Burma mai neve?','4'),
('Mit jelent Ulánbátor Mongólia fővárosának neve?','4'),
('Melyik kontinenshez tartoznak a Kókusz-szigetek?','4'),
('Melyik országban van a Gyöngy-folyó?','4'),
('Mennyi Budapest lakossága?','4'),
('Milyen hosszú a Lánchíd Budapesten?','4'),
('Mikor volt a kiegyezés?','4'),
('Kit száműztek 1815-ben Szent-Ilona szigetére?','4'),
('Mi a Himalája szó jelentése?','4'),
('Melyik a Föld második legmagasabb hegycsúcsa?','4'),
('Hány négyzetkilométer a Yellowstone Nemzeti Park az USA-ban?','4'),
('Melyik Magyarország legmagasabb hegysége?','4'),
('Melyik hegységünk csúcsa Írott-kő?','4'),
('Mi a Mecsek legmagasabb csúcsa?','4'),
('Melyik pápa kezdeményezésére jött létre a Szent Liga?','4'),
('Melyik ország határolja nyugaton Indiát?','4'),
('Melyik a világ legnagyobb öble?','4'),
('Melyik hegység egyik hegycsúcsa a Matterhorn?','4'),
('Hány km hosszú a Kebele-patak?','4'),
('Melyik megyében van Pannonhalma?','4'),
('Melyik folyó mellékfolyója a Hernád?','4'),
('Mi a sárospataki vár másik elnevezése?','4'),
('Hány országon halad át a Duna?','4'),
('Melyik nem a Kisalföld régi elnevezése?','4'),
('Hány négyzetkilóméter a Kisalföld teljes területe?','4'),
('Melyik városban található a Victor Vasarely Múzeum?','4'),
('Melyik város nem Szabolcs-Szatmár-Bereg megyében van?','4'),
('Melyik amerikai államban van az Alcatraz-sziget?','4'),
('Hány méter a teljes hosszúsága a Golden Gate hídnak?','4'),
('Melyik bankjegy hátoldalán látható a Sárospataki vár?','4'),
('Mi Bács-Kiskun megye székhelye?','4'),
('Melyik városunkban található a Csonka-torony?','4'),
('Mi volt Srí Lanka régi elnevezése?','4'),
('Mit jelent magyarul a Srí Lanka elnevezés?','4'),
('Melyik király korában élt Janus Pannonius?','4'),
('Melyik városban van az 56-os Múzeum?','4'),
('Melyik ország határolja északról Nógrád megyét?','4'),
('Milyen hosszú a Kárpátok?','4'),
('Melyik skálán mérik a szél sebességét?','4'),
('Mi a tornádó?','4'),
('Melyik országhoz tartozik Korzika szigete?','4'),
('Mi volt Thaiföld régi neve?','4'),
('Melyik ország szigete Ibiza?','4'),
('Mi Hawaii állam székhelye?','4'),
('Melyik amerikai államban van Miami?','4'),
('Melyik város van Kalifornia államban?','4'),
('Melyik folyó táplálja a Balatont?','4'),
('Melyik megye területén van Göcsej?','4'),
('Melyik magyar hegymászó mászta meg a Csomolungmát?','4'),
('Melyik ország nem tartozik a skandináv államok közé?','4'),
('Melyik országban van a Ladoga-tó?','4'),
('Mi Finnország fővárosa?','4'),
('Melyik tenger nyúlványa a Botteni-öböl?','4'),
('Milyen magas a Kab-hegy?','4'),
('Mi Banglades hivatalos nyelve?','4'),
('Hol található a Planetárium Budapesten?','4'),
('Milyen hosszú a Szuezi-csatorna?','4'),
('Mikor adták át a Megyeri-hidat Budapesten?','4'),
('Budapest hanyadik kerületében van a Budavári Palota?','4'),
('Mi Szabolcs-Szatmár-Bereg megye székhelye?','4'),
('Melyik megyében van Mezőkövesd?','4'),
('Melyik ország határolja északról Nógrád-megyét?','4'),
('Milyen magas a Galya-tető?','4'),
('Melyik megyében van a siroki vár?','4'),
('Melyik folyó mellékfolyója a Zagyva?','4'),
('Melyik ország folyója még Magyarországon kívűl a Dráva?','4'),
('Melyik amerikai államban van Portland?','4'),
('Melyik amerikai államban van egy Budapest nevű település?','4'),
('Melyik amerikai városban van a John F. Kennedy nemzetközi repülőtér?','4'),
('Hány méter az Eiffel-torony?','4'),
('Melyik városban akarták eredetileg felépíteni az Eiffel-tornyot?','4'),
('Milyen magas a párizsi Diadalív?','4'),
('Melyik király rezidenciája volt a versailles-i kastély?','4'),
('Melyik országgal határos Monaco?','4'),
('Melyik két szín van Spanyolország zászlajában?','4'),
('Melyik tenger öble a Tarantói-öböl?','4'),
('Melyik tenger határolja északon Európát?','4'),
('Hány ország van Európában?','4'),
('Milyen hosszú a Volga folyó?','4'),
('Mi a trópusi ciklon neve a Távol-Keleten?','4'),
('Honnan fúj a Sirokkó szélfajta?','4'),
('Hány kerület van Budapesten?','4'),
('Melyik folyó osztja két részre Budapestet?','4'),
('Milyen hosszú a Margit-híd?','4'),
('Mikor épült a budapesti Libegő?','4'),
('Melyik kontinensen van a Kilimandzsáró?','4'),
('Hányszor nagyobb a Szahara sivatag hazánknál?','4'),
('Hány ország területén halad keresztül a Nílus folyó?','4'),
('Mit jelent magyarul a Nílus szó?','4'),
('Milyen hosszú Afrikában a Tanganyika-tó?','4'),
('Melyik amerikai államból ered a Rio Grande folyó?','4'),
('Milyen hosszú az Egyenlítő?','4'),
('Melyik országban van a pisai ferde torony?','4'),
('Hány emelete van a pisai ferde toronynak?','4'),
('Melyik megyében van Szigetköz?','4'),
('Melyik király katonája volt Búvár Kund?','4'),
('Mi a Viharsarok?','4'),
('Hány főből áll Vatikán népessége?','4'),
('Hol található a Sixtus-kápolna?','4'),
('Milyen magas a Colosseum?','4'),
('Mi a neve a londoni Westminster-palota toronyórája harangjának?','4'),
('Mi a London Eye másik elnevezése?','4'),
('Hány fülkéből áll a London Eye?','4'),
('Melyik városban látható a Prado?','4'),
('Mi a déli-sarkvidék neve?','4'),
('Milyen állat van Grönland címerén?','4'),
('Melyik a Föld második legnagyobb kontinense?','4'),
('Hol van a Tűzföld?','4'),
('Milyen hosszú a Magellán-szoros?','4'),
('Melyik községbe született Kossuth Lajos?','4'),
('Minek a neve a Farkaslyuk?','4'),
('Melyik országban van az Altamira-barlang?','4'),
('Melyik városban van a Fehér-ház?','4'),
('Milyen alakú a Pentagon?','4'),
('Mi a Kék Mauritius?','4'),
('Hány méter magas a London Eye?','4'),
('Milyen hosszú a Balaton?','4'),
('Melyik országban van Karlstad?','4'),
('Melyik országban van a Stonehenge?','4'),
('Milyen hosszú a Tisza magyarországi szakasza?','4'),
('Melyik folyó mellékvize a Tarna?','4'),
('Melyik kontinensen élnek a busmanok?','4'),
('Melyik két színből áll Ausztria zászlaja?','4'),
('Melyik ország a világ legnagyobb kávétermelője?','4'),
('Milyen szín nincs Franciaország zászlajában?','4'),
('Melyik félszigeten fekszik Montenegro?','4'),
('Hány vulkán található Kamcsatka területén?','4'),
('Melyik településen épül fel az ország legnagyobb betleheme?','4'),
('Melyik kontinensen van Peru?','4'),
('Melyik szín nem található meg Finnország zászlajában?','4'),
('Hány kerület van New Yorkban?','4'),
('Milyen hosszú a Fogarasi-havasok?','4'),
('Melyik ország zászlaja a fehér alapon piros kör?','4'),
('Melyik országban kerül átadásra a Nobel-békedíj?','4'),
('Melyik ország zászlaja nem két színből áll?','4'),
('Hol van Genova?','4'),
('Melyik megyében van Solymár?','4'),
('Hány országra terjed ki az Alföld?','4'),
('Melyik sziget neve volt régebben Formosa?','4'),
('Melyik a Föld második legnagyobb szigete?','4'),
('Mekkora a Duna magyarországi szakaszának a hossza?','4'),
('Melyik országhoz tartozik a Bermuda szigetcsoport?','4'),
('Melyik hurrikán okozott 2005-ben nagy károkat?','4'),
('Mióta az Egyesült Királyság királynője II. Erzsébet?','4'),
('Melyik tó nem az afrikai Nagy-Tavak egyike?','4'),
('Melyik tengeren fekszik Ibiza?','4'),
('Melyik folyón van a Vaskapu-szoros?','4'),
('Melyik tengerben fekszik a Kis-Antillák szigetcsoport?','4'),
('Mi Zimbabwe fővárosa?','4'),
('Hol található a Machu Picchu?','4'),
(' Melyik ország fővárosa Helsinki?','4'),
(' Milyen hosszú a Balaton?','4'),
(' Melyik ország része a Vajdaság?','4'),
(' Melyik két ország folyója a Kraszna?','4'),
(' Melyik megyében van Kocsord?','4'),
(' Melyik városban van a schönbrunni kastély?','4'),
(' Melyik király zarándoklatát nevezzük Canossa-járásnak?','4'),
(' Hány színből áll Hollandia zászlaja?','4'),
(' Mi határolja keletről Argentinát?','4'),
(' Melyik ország tartománya Manitoba?','4'),
(' Melyik városban van a Hyde-Park?','4'),
(' Melyik városban van a La Scala Operaház?','4'),
(' Mi Somogy-megye székhelye?','4'),
(' Melyik ország szigete Jáva?','4'),
(' Melyik két színből áll Izland zászlaja?','4'),
(' Milyen hosszú a Tisza?','4'),
(' Melyik városban található a Buckingham-palota?','4'),
(' Melyik országban van Ho Si Minh-város?','4'),
(' Melyik megyében van Almásfüzitő?','4'),
(' Melyik államban van a Pentagon?','4'),
(' Hány országon folyik keresztül a Nílus?','4'),
(' Mi a Fülöp-szigetek fővárosa?','4'),
(' Melyik ország regiója Kárpátalja?','4'),
(' Melyik országban van az Appalache-hegység?','4'),
(' Milyen alakú a Sínai-félsziget?','4'),
(' Hol székel a Világbank?','4'),
(' Melyik kontinensen van Burkina Faso?','4'),
(' Melyik országban van Granada?','4'),
(' Melyik folyó partján terül el London?','4'),
(' Milyen hosszú a Szajna folyó?','4'),
(' Melyik országhoz tartoznak az Azori-szigetek?','4'),
(' Melyik ország határolja délen Brazíliát?','4'),
(' Melyik szín nem található meg Belgium zászlajában?','4'),
(' Melyik városunkban található a Memento Park?','4'),
(' Hol található Budapesten a Halászbástya?','4'),
(' Mit jelent a Citadella szó?','4'),
(' Hány piramisból állnak a Gízai piramisok?','4'),
(' Mikor adták át a Kiskörei-víztározót?','4'),
(' Melyik országhoz tartozik Bácska túlnyomó része?','4'),
(' Mi Burkina Faso nevének jelentése?','4'),
(' Mennyi a teljes hosszúsága a londoni Tower Bridge-nek?','4'),
(' Mi Alamaba állam székhelye?','4'),
(' Melyik országban van a Muszala hegycsúcs?','4'),
(' Melyik magyarországi település fekszik hármashatár mellett?','4'),
(' Melyik városban található a Pantheon?','4'),
(' Melyik megye nem szomszédja Somogy megyének?','4'),
(' Hány csillag van Honduras zászlaján?','4'),
(' Hol található a Kékfestő Múzeum?','4'),
(' Milyen hosszú a Bering-szoros?','4'),
(' Milyen hosszú a Limpopo folyó?','4'),
(' Melyik amerikai állam fekszik a legdélebben?','4'),
(' Hány km a Balatonpart?','4'),
(' Melyik ország felé fúj a "Bóra" szél?','4'),
(' Hány ország területét foglalja el a Szahara sivatag?','4'),
(' Hol él a Loch Ness-i szörny a legenda szerint?','4'),
(' Melyik várost szokták a bajor velencének is nevezni?','4'),
(' Milyen magas az Annapurna?','4'),
(' A tudósok szerint mi lehetne a nyolcadik kontinens?','4'),
(' Melyik szín nem található meg Írország zászlajában?','4'),
(' Budapest után melyik a legnépesebb város Magyarországon?','4'),
(' Melyik ország nem tartozik a Balti országok közé?','4'),
(' Melyik a legnépesebb ország a Földön?','4'),
(' Mi Jamaica nevének jelentése?','4'),
(' Melyik országban van Karlovy Vary?','4'),
(' Melyik ország határolja északról Magyarországot?','4'),
(' Hány kontinens veszi körbe a Földközi-tengert?','4'),
(' Melyik óceánban található a Seychelle-szigetek?','4'),
(' Melyik a legnagyobb bauxittermelő ország?','4'),
(' Melyik tenger partján fekszik Bulgária?','4'),
(' Melyik ország nem Borneó szigetén van?','4'),
(' Mi volt a budapesti Szabadság híd eredeti neve?','4'),
(' Melyik ország zászlaja nem téglalap alakú?','4'),
(' Hol fordul elő Magyarországon feketekőszén?','4'),
(' Mekkora a teljes magassága a New Yorki Szabadság szobornak?','4'),
(' Hegyeshalomnál melyik országba tudunk átkelni?','4'),
(' Melyik ország nem tartozik a latin-amerikai országok közé?','4'),
(' Hol van a Kruger Nemzeti Park?','4'),
(' Melyik városban látható a Megváltó Krisztus szobra Brazíliában?','4'),
(' Mi a Feszty-körkép eredeti címe?','4'),
(' Melyik Magyarország legdélebben fekvő városa?','4'),
(' Melyik megyében van Bugyi község?','4'),
(' Hány napig volt a Balaton a leghosszabb ideig befagyva?','4'),
(' Milyen hoszzú a budapesti Árpád-híd?','4'),
(' Melyik amerikai állam székhelye Boston?','4'),
(' Melyik országnál ömlik az Atlanti-óceánba az Amazonas?','4'),
(' Melyik falunak van egy lakosa?','4'),
(' Mi Dél-Amerika legdélibb pontja?','4'),
(' Melyik megyében van Karakószörcsök?','4'),
(' Hol látható a Festetics-kastély?','4'),
(' Melyik Magyarország legnagyobb kiterjedésű borvidéke?','4'),
(' Melyik megye folyói a Rába Gyöngyös Répce Marcal?','4'),
(' Hol látható az "Óriások útja"?','4'),
(' Milyen hosszú a Viktória-tó?','4'),
(' Hány kerülete van Budapestnek?','4'),
(' Melyik országban van Stuttgart?','4'),
(' Hol látható a Millenniumi emlékmű Budapesten?','4'),
(' Melyik nem Dél-Amerikai ország?','4'),
(' Mi Komárom-Esztergom megye székhelye?','4'),
(' Kiknek az arcmását vésték az amerikai Rushmore-hegy oldalába?','4'),
(' Melyik városban látható a Laokoón-csoport szobor?','4'),
(' Mi van Kanada zászlaján?','4'),
(' Mi Uruguay fővárosa?','4'),
(' Milyen állat nincs Budapest címerében?','4'),
(' Melyik megyében van Zala község?','4'),
(' Melyik Magyarország leghosszabb hídja?','4'),
(' Ki követte Károly Róbertet a trónon?','4'),
(' Hol látható a Csontváry Múzeum?','4'),
(' Melyik országban látható a Sierra Nevada hegység?','4'),
(' Melyik nem New York városrésze?','4'),
(' Hanyadik kerület Ferencváros Budapesten?','4'),
(' Melyik országban van Granada?','4'),
(' Mikor tört ki utoljára a Vezúv?','4'),
(' Mik találhatók Madame Tussaud panoptikumában?','4'),
(' Melyik ország fennhatósága alatt áll Grönland?','4'),
(' Milyen hosszú az Erzsébet-híd?','4'),
(' Milyen magas a pécsi tévétorony?','4'),
(' Melyik nem Balaton parti település?','4'),
(' Melyik téren található Budapesten az Országház?','4'),
(' Melyik hegységben található az Ördögmalom-vízesés?','4'),
(' Mi volt Irán régi neve?','4'),
(' Melyik országban van Dubaj?','4'),
(' Melyik Nemzeti Park része a Káli-medence?','4'),
(' Melyik megyében van Makkoshotyka?','4'),
(' Melyik európai országban látható a heidelbergi várkastély?','4'),
(' Mi Angola fővárosa?','4'),
(' Milyen madár látható Heves megye címerében?','4'),
(' Melyik balatoni település közelében van a Pántlika kastély?','4'),
(' Hol látható a Kovács Margit Múzeum?','4'),
(' Hány dombra épült Róma?','4'),
(' Melyik nem ázsiai ország?','4'),
(' Hol található a Grand Canyon?','4'),
(' Melyik európai fővárost nevezik "arany városnak"?','4'),
(' Melyik megyében van Kömpöc?','4'),
(' Melyik városban van a Szent Márk-bazilika?','4'),
(' Melyik ország fővárosa Havanna?','4'),
(' Hol látható a Golden Gate híd?','4'),
(' Melyik megyében van Nyúl nevű település?','4'),
(' Melyik óceánban van a Húsvét-sziget?','4'),
(' Hány km-re fekszik Sopron Bécstől?','4'),
(' Hány méter magas a Hármashatár-hegy?','4'),
(' Melyik országban van Petra romvárosa?','4'),
(' Melyik ország a világ legnagyobb banánexportőre?','4'),
(' Melyik ország nem a Perzsa-öböl partján van?','4'),
(' Hol látható a Sagrada Família a Szent Család-templom?','4'),
(' Hány kilométer hosszú a Balaton?','4'),
(' Melyik Brazília folyója?','4'),
(' Hol van Bali szigete?','4'),
(' Mi a Föld legmélyebb pontja?','4'),
(' Hány emelete van az Empire State Buildingnek?','4'),
(' Melyik a Föld leghosszabb szélességi köre?','4'),
(' Melyik országban van az Április 25. híd?','4'),
(' Hol van a Labrador félsziget?','4'),
(' Melyik városban található az Ermitázs?','4'),
(' Ki volt I. Szent István édesanyja?','4'),
(' Melyik megye székhelye Miskolc?','4'),
(' Hol található Indiában a Tádzs Mahal?','4'),
(' Melyik a világ legnagyobb öble?','4'),
(' Hol látható a Három-szurdok-gát?','4'),
(' Milyen magas a János-hegy?','4'),
(' Melyik európai fővárosban van a Piccadilly Circus?','4'),
(' Melyik nem egy amerikai állam?','4'),
(' Melyik ország területén van Erdély?','4'),
(' Melyik állam nem tartozik az ABC államok közé?','4'),
(' Melyik folyó partján fekszik Bécs?','4'),
(' Melyik megyében van Balaton nevű település?','4'),
(' Melyik ország fővárosa Bamako?','4'),
(' Melyik városban van a Déri múzeum?','4'),
(' Melyik ország zászlaja nem három színből áll?','4'),
(' Melyik ország városai Hannover és Düsseldorf?','4'),
(' Hol van Mozart szülőháza?','4'),
(' Ki tervezte a Magyar Nemzeti Múzeumot?','4'),
(' Mi volt Srí Lanka régi elnevezése?','4'),
(' Mi az Északi-sarkvidék neve?','4'),
(' Hol található a Szahara sivatag?','4'),
(' Mi Uruguay fővárosa?','4'),
(' Melyik ország fekszik az Egyenlítő vonalán?','4'),
(' Mi az Andok legmagasabb pontja?','4'),
(' Melyik megyében van Hatvan?','4'),
(' Melyik városban van a Horror Színház?','4'),
(' Mi választja el Spanyolországot Marokkótól?','4'),
(' Mi Alamaba állam székhelye?','4'),
(' Mi az Egyesült Államok nemzeti állata?','4'),
(' Melyik ország a legnagyobb burgonyafogyasztó a világon?','4'),
(' Melyik megye székhelye Szeged?','4'),
(' Mi a neve a szegedi múzeumnak?','4'),
(' Melyik ország nem szomszédos Svájccal?','4'),
(' Melyik tenger nem tartozik a Hét tenger közé?','4'),
(' Melyik évben csatlakozott Magyarország az Európai Unióhoz?','4'),
(' Melyik városban látható a Petronas-ikertorony?','4'),
(' Denver melyik amerikai állam székhelye?','4'),
(' Mi Zimbabwe fővárosa?','4'),
(' Melyik országon nem halad keresztül a Duna?','4'),
(' Melyik amerikai állam fekszik a legdélebben?','4'),
(' Hány km a Balatonpart?','4'),
(' Hány ország területét foglalja el a Szahara sivatag?','4'),
(' Hol él a Loch Ness-i szörny a legenda szerint?','4'),
(' Melyik várost szokták a bajor velencének is nevezni?','4'),
(' Melyik a legnépesebb ország a Földön?','4'),
(' Melyik nem tartozik a világ hét csodája közé?','4'),
(' Melyik megyében van Csanádapáca?','4'),
(' Melyik két óceánt köti össze a Drake-átjáró?','4'),
(' Mi Argentína hivatalos nyelve?','4'),
(' Melyik országban van a kölni dóm?','4'),
(' Mi Ázsia legmagasabb csúcsa?','4'),
(' Melyik nem Balaton-parti település?','4'),
(' Mi Mongólia fővárosa?','4'),
(' Melyik kontinensen van Etiópia?','4'),
(' Milyen szín nincs Csehország zászlajában?','4'),
(' Melyik városban található a Buckingham-palota?','4'),
(' Melyik településen épül fel az ország legnagyobb betleheme?','4'),
(' Melyik államban van a Pentagon?','4'),
(' Mi Komárom-Esztergom megye székhelye?','4'),
(' Hol található a Rushmore-hegy?','4'),
(' Milyen állat látható Pest-megye címerében?','4'),
(' Melyik amerikai államban van a Grand Canyon?','4'),
(' Hány km a Mississippi folyó?','4'),
(' Melyik a Föld 3. legnagyobb szigete?','4'),
(' Hol van Kalotaszeg?','4'),
(' Melyik városban van Katona József Színház?','4'),
(' Melyik ország nem tartozik a Benelux államok közé?','4'),
(' Mi volt Isztambul régi neve?','4'),
(' Melyik országban van Rotterdam?','4'),
(' Mi Egyiptom fővárosa?','4'),
(' Melyik országban van a Gyilkos-tó?','4'),
(' Melyik egy hurrikán neve?','4'),
(' Melyik város történelmi negyede a Hradzsin?','4'),
(' Melyik országban van Montreal?','4'),
(' Melyik kontinensen helyezkedik el Botswana?','4'),
(' Mi Horvátország fővárosa?','4'),
(' Melyik két kontinens között helyezkedik el a Vörös-tenger?','4'),
(' Mik állnak a budapesti Memento Parkban?','4'),
(' Melyik állam nem tartozik az USA alapító államai közé?','4'),
(' Melyik a legnagyobb területű megyénk?','4'),
(' Melyik nemzeti park nem létezik?','4'),
(' Melyik megyében van Lakitelek?','4'),
(' Melyik országon nem folyik keresztül a Tisza?','4'),
(' Melyik ország a világ legnagyobb banánexportőre?','4'),
(' Budapest melyik terén van az óriáskerék?','4'),
(' Melyik városban van a Brooklyn híd?','4'),
(' Melyik borvidék nem létezik?','4'),
(' Melyik folyó két partján fekszik Bécs?','4'),
(' Hol látható a Hagia Szophia székesegyház?','4'),
(' Melyik kastély látható Nagycenken?','4'),
(' Melyik országban van a Kilimandzsáró?','4'),
(' Melyik szélességi kör osztja ketté Mexikót?','4'),
(' Mikor volt a kiegyezés?','4'),
(' Mi Nógrád megye székhelye?','4'),
(' Hol található Budapesten a Halászbástya?','4'),
(' Melyik város nevezetessége a Big Ben?','4'),
(' Melyik államban van Dallas?','4'),
(' Jelenleg hány tagállama van az Európai Uniónak?','4'),
(' Hol van a Zöld-fok?','4'),
(' Melyik városba jutunk ha az M6-os autópályán megyünk Budapestről?','4'),
(' Melyik egy létező település?','4'),
(' Budapest hanyadik kerülete Csepel?','4'),
(' Hány kerülete van New Yorknak?','4'),
(' Melyik országban található Leszbosz szigete?','4'),
(' Melyik nem megyei jogú város?','4'),
(' Megközelítőleg hány éves a világ legidősebb fája a "Matuzsálem fa"?','4'),
(' Miről kapta nevét Kambodzsa?','4'),
(' Melyik országgal határos egyedül Monaco?','4'),
(' Melyik hegységben van a Prédikálószék?','4'),
(' Melyik országhoz van legközelebb a Seychelle-szigetek?','4'),
(' Melyik község része Dobogó-kő?','4'),
(' Melyik folyó mellékfolyója a Szamos?','4'),
(' Hol van Kézdivásárhely és Sepsiszentgyörgy?','4'),
(' Hol hullik a Földön a legkevesebb csapadék?','4'),
(' Hol van Magyarországon a Csillagvár?','4'),
(' Hol található a Wembley Stadion?','4'),
(' Melyik amerikai elnök arcmása nincs a Rushmore-hegy oldalába vésve?','4'),
(' Melyik hegység része Drégely vára?','4'),
(' Melyik városhoz van legközelebb Kópháza?','4'),
(' Hol van Szászország?','4'),
(' Mi választja el Spanyolországot Marokkótól?','4'),
(' Melyik ország nem tartozik a Balti országok közé?','4'),
(' Melyik tenger beltengere a Ligur-tenger?','4'),
(' Hol látható a Sziklás-hegység(Rocky Mountains)?','4'),
(' Mi a neve Velence leghíresebb hídjának?','4'),
(' Mi Venezuela fővárosa?','4'),
(' Hol található a Pitti-palota?','4'),
(' Melyik megyében van Egerszalók?','4'),
(' Melyik fővárost szokták úgy emlegetni mint "a harmadik Róma"?','4'),
(' Mi a Csomolungma hegység nevének a jelentése?','4'),
(' Hol látható a "Királyok völgye"?','4'),
(' Budapest hanyadik kerülete Zugló?','4'),
(' Hol található a Téli Palota?','4'),
(' Hol található a Bikini-atoll?','4'),
(' Hol van a Takla-Makán sivatag?','4'),
(' Milyen épület a "Shanghai Tower" Kínában?','4'),
(' Melyik szigeten született Bonaparte Napóleon?','4'),
(' Mi Somogy-megye székhelye?','4'),
(' Hol látható a Sonora-sivatag?','4'),
(' Mi a Budavári Sikló két kocsijának a neve?','4'),
(' Melyik ország nem Jugoszlávia utódállama?','4'),
(' Milyen szín nincs Franciaország zászlajában?','4'),
(' Melyik tenger nyúlványa a Botteni-öböl?','4'),
(' Ki találta meg a holt-tengeri tekercsek első darabjait?','4'),
(' Honnan indul a János-hegyre a budapesti Libegő?','4'),
(' Mi Algéria hivatalos nyelve?','4'),
(' Melyik országban van a Delta Works nevű gátrendszer?','4'),
(' Melyik város régi neve volt Oradea?','4'),
(' Melyik ország városa Krakkó?','4'),
(' Melyik megyében van Balassagyarmat?','4'),
(' Ki a rendezője a Terminátor c. filmnek?','4'),
(' Hol látható a Cifrapalota?','4'),
(' Milyen otthon van Veresegyházán?','4'),
(' Melyik két település között fut a Kőröshegyi völgyhíd?','4'),
(' Melyik városunkban található a Munkácsy Mihály Múzeum?','4'),
(' Az alábbiak közül melyik országon halad át a Tisza?','4'),
(' Melyik államban van Beverly Hills?','4'),
(' Melyik megyében van Csanádpalota?','4'),
(' Melyik országba jutunk ha Letenyénél szeretnénk átkelni a határon?','4'),
(' Mi a Szent Jakab-út másik elnevezése?','4'),
(' Melyik országban van Besztercebánya és Nagyszombat?','4'),
(' Melyik a Föld második legnépesebb országa?','4'),
(' Hol látható Pamukkale a ritka természeti képződmény?','4');

GO


