//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRF_Quiz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public long AnswerID { get; set; }
        public string A1Text { get; set; }
        public string A2Text { get; set; }
        public string A3Text { get; set; }
        public string AnswerText { get; set; }
        public int CorrectAnswer { get; set; }
        public long QuestionID { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
